syntax = "proto3";

package incident;

// Service pour la gestion des incidents
service IncidentService {
  // La Gateway envoie un log pour analyse
  rpc ProcessLog (LogRequest) returns (LogResponse);
  // La Gateway demande la liste des alertes critiques
  rpc GetAlerts (AlertRequest) returns (AlertStream);
}

message LogRequest {
  string source_ip = 1;
  string event_type = 2; // ex: "Login Attempt", "Port Scan"
  string payload = 3;
  string timestamp = 4;
}

message LogResponse {
  string status = 1; // ex: "Log Received"
  bool is_suspicious = 2;
}

message AlertRequest {
  string min_severity = 1;
}

message AlertStream {
  repeated Incident incidents = 1;
}

message Incident {
  string id = 1;
  string description = 2;
  string severity = 3;
}
